[phases.setup]
nixPkgs = ["chromium", "chromedriver", "python311"]

[phases.build]
cmds = ["python -m venv /app/.venv", "/app/.venv/bin/pip install -r requirements.txt"]

[start]
cmd = "python bot.py"
