[phases.setup]
nixPkgs = ["chromium", "chromedriver", "python310"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
# Añadimos las rutas de Nix al PATH antes de arrancar el bot
cmd = "PATH=$PATH:/usr/bin:/nix/var/nix/profiles/default/bin python bot.py"
