[variables]
    PYTHON_VERSION = "3.10"

[phases.setup]
    nixPkgs = ["chromium", "chromedriver", "python310"]

[phases.build]
    cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
    cmd = "python bot.py"
